name: Baital Test Deploy

on:
  push:
    branches: [testmaster]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Send to server
        uses: "appleboy/scp-action@master"
        with:
          host: "194.146.43.119"
          username: "root"
          password: ${{secrets.TEST_SERVER_PASSWORD}}
          port: "22"
          source: ".nuxt,nuxt.config.js,package.json,assets,static"
          target: "/var/www/front"

      - name: Run project in server
        uses: "appleboy/ssh-action@master"
        with:
          host: "194.146.43.119"
          username: "root"
          password: ${{secrets.TEST_SERVER_PASSWORD}}
          port: "22"
          script: |
            cd /var/www/front
            npm install
            npm audit fix
            pm2 delete all
            pm2 start npm --name "smart_satu.kz" -- run start
            systemctl restart nginx
